spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/study_kotlin

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
        use_sql_comments: true



logging.level.org.hibenrate.type.descriptor:
  sql: trace